# Generated by Django 2.2.5 on 2019-10-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0002_auto_20191022_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(max_length=20),
        ),
    ]
